# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='recommend.proto',
  package='com.github.rerost.recommend_scouter.example.with_python.api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0frecommend.proto\x12;com.github.rerost.recommend_scouter.example.with_python.api\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8b\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05score\x18\x02 \x01(\x01\x12h\n\x11score_description\x18\x03 \x01(\x0b\x32M.com.github.rerost.recommend_scouter.example.with_python.api.ScoreDescription\"e\n\x11ListUsersResponse\x12P\n\x05users\x18\x01 \x03(\x0b\x32\x41.com.github.rerost.recommend_scouter.example.with_python.api.User\"\x8b\x01\n\x04\x42log\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05score\x18\x02 \x01(\x01\x12h\n\x11score_description\x18\x03 \x01(\x0b\x32M.com.github.rerost.recommend_scouter.example.with_python.api.ScoreDescription\"e\n\x11ListBlogsResponse\x12P\n\x05\x62logs\x18\x01 \x03(\x0b\x32\x41.com.github.rerost.recommend_scouter.example.with_python.api.Blog\"8\n\x05Score\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x12\n\nscore_func\x18\x03 \x01(\t\"z\n\x10ScoreDescription\x12R\n\x06scores\x18\x01 \x03(\x0b\x32\x42.com.github.rerost.recommend_scouter.example.with_python.api.Score\x12\x12\n\nscore_func\x18\x02 \x01(\t2\x9e\x02\n\x10RecommendService\x12\x83\x01\n\tListUsers\x12\x16.google.protobuf.Empty\x1aN.com.github.rerost.recommend_scouter.example.with_python.api.ListUsersResponse\"\x0e\x82\xd3\xe4\x93\x02\x08\x12\x06/users\x12\x83\x01\n\tListBlogs\x12\x16.google.protobuf.Empty\x1aN.com.github.rerost.recommend_scouter.example.with_python.api.ListBlogsResponse\"\x0e\x82\xd3\xe4\x93\x02\x08\x12\x06/blogsb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_USER = _descriptor.Descriptor(
  name='User',
  full_name='com.github.rerost.recommend_scouter.example.with_python.api.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.github.rerost.recommend_scouter.example.with_python.api.User.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='com.github.rerost.recommend_scouter.example.with_python.api.User.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score_description', full_name='com.github.rerost.recommend_scouter.example.with_python.api.User.score_description', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=279,
)


_LISTUSERSRESPONSE = _descriptor.Descriptor(
  name='ListUsersResponse',
  full_name='com.github.rerost.recommend_scouter.example.with_python.api.ListUsersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='users', full_name='com.github.rerost.recommend_scouter.example.with_python.api.ListUsersResponse.users', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=382,
)


_BLOG = _descriptor.Descriptor(
  name='Blog',
  full_name='com.github.rerost.recommend_scouter.example.with_python.api.Blog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.github.rerost.recommend_scouter.example.with_python.api.Blog.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='com.github.rerost.recommend_scouter.example.with_python.api.Blog.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score_description', full_name='com.github.rerost.recommend_scouter.example.with_python.api.Blog.score_description', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=524,
)


_LISTBLOGSRESPONSE = _descriptor.Descriptor(
  name='ListBlogsResponse',
  full_name='com.github.rerost.recommend_scouter.example.with_python.api.ListBlogsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blogs', full_name='com.github.rerost.recommend_scouter.example.with_python.api.ListBlogsResponse.blogs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=627,
)


_SCORE = _descriptor.Descriptor(
  name='Score',
  full_name='com.github.rerost.recommend_scouter.example.with_python.api.Score',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.github.rerost.recommend_scouter.example.with_python.api.Score.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='com.github.rerost.recommend_scouter.example.with_python.api.Score.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score_func', full_name='com.github.rerost.recommend_scouter.example.with_python.api.Score.score_func', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=629,
  serialized_end=685,
)


_SCOREDESCRIPTION = _descriptor.Descriptor(
  name='ScoreDescription',
  full_name='com.github.rerost.recommend_scouter.example.with_python.api.ScoreDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scores', full_name='com.github.rerost.recommend_scouter.example.with_python.api.ScoreDescription.scores', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score_func', full_name='com.github.rerost.recommend_scouter.example.with_python.api.ScoreDescription.score_func', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=687,
  serialized_end=809,
)

_USER.fields_by_name['score_description'].message_type = _SCOREDESCRIPTION
_LISTUSERSRESPONSE.fields_by_name['users'].message_type = _USER
_BLOG.fields_by_name['score_description'].message_type = _SCOREDESCRIPTION
_LISTBLOGSRESPONSE.fields_by_name['blogs'].message_type = _BLOG
_SCOREDESCRIPTION.fields_by_name['scores'].message_type = _SCORE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['ListUsersResponse'] = _LISTUSERSRESPONSE
DESCRIPTOR.message_types_by_name['Blog'] = _BLOG
DESCRIPTOR.message_types_by_name['ListBlogsResponse'] = _LISTBLOGSRESPONSE
DESCRIPTOR.message_types_by_name['Score'] = _SCORE
DESCRIPTOR.message_types_by_name['ScoreDescription'] = _SCOREDESCRIPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'recommend_pb2'
  # @@protoc_insertion_point(class_scope:com.github.rerost.recommend_scouter.example.with_python.api.User)
  ))
_sym_db.RegisterMessage(User)

ListUsersResponse = _reflection.GeneratedProtocolMessageType('ListUsersResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTUSERSRESPONSE,
  __module__ = 'recommend_pb2'
  # @@protoc_insertion_point(class_scope:com.github.rerost.recommend_scouter.example.with_python.api.ListUsersResponse)
  ))
_sym_db.RegisterMessage(ListUsersResponse)

Blog = _reflection.GeneratedProtocolMessageType('Blog', (_message.Message,), dict(
  DESCRIPTOR = _BLOG,
  __module__ = 'recommend_pb2'
  # @@protoc_insertion_point(class_scope:com.github.rerost.recommend_scouter.example.with_python.api.Blog)
  ))
_sym_db.RegisterMessage(Blog)

ListBlogsResponse = _reflection.GeneratedProtocolMessageType('ListBlogsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTBLOGSRESPONSE,
  __module__ = 'recommend_pb2'
  # @@protoc_insertion_point(class_scope:com.github.rerost.recommend_scouter.example.with_python.api.ListBlogsResponse)
  ))
_sym_db.RegisterMessage(ListBlogsResponse)

Score = _reflection.GeneratedProtocolMessageType('Score', (_message.Message,), dict(
  DESCRIPTOR = _SCORE,
  __module__ = 'recommend_pb2'
  # @@protoc_insertion_point(class_scope:com.github.rerost.recommend_scouter.example.with_python.api.Score)
  ))
_sym_db.RegisterMessage(Score)

ScoreDescription = _reflection.GeneratedProtocolMessageType('ScoreDescription', (_message.Message,), dict(
  DESCRIPTOR = _SCOREDESCRIPTION,
  __module__ = 'recommend_pb2'
  # @@protoc_insertion_point(class_scope:com.github.rerost.recommend_scouter.example.with_python.api.ScoreDescription)
  ))
_sym_db.RegisterMessage(ScoreDescription)



_RECOMMENDSERVICE = _descriptor.ServiceDescriptor(
  name='RecommendService',
  full_name='com.github.rerost.recommend_scouter.example.with_python.api.RecommendService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=812,
  serialized_end=1098,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListUsers',
    full_name='com.github.rerost.recommend_scouter.example.with_python.api.RecommendService.ListUsers',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_LISTUSERSRESPONSE,
    serialized_options=_b('\202\323\344\223\002\010\022\006/users'),
  ),
  _descriptor.MethodDescriptor(
    name='ListBlogs',
    full_name='com.github.rerost.recommend_scouter.example.with_python.api.RecommendService.ListBlogs',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_LISTBLOGSRESPONSE,
    serialized_options=_b('\202\323\344\223\002\010\022\006/blogs'),
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMMENDSERVICE)

DESCRIPTOR.services_by_name['RecommendService'] = _RECOMMENDSERVICE

# @@protoc_insertion_point(module_scope)
